name = "TestPackage"
uuid = "4867a700-4c73-4be4-87fc-d2ed8af71add"
authors = ["Ramil Khusainov"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
